### ISSUE TITLE
Upgrade to latest ROOT and YODA packages

### ISSUE THREAD

**Issue by alisonrclarke** [HEPData/hepdata-converter-docker#7]
Check whether we're still using the most appropriate version of the ROOT package (Conda vs Ubuntu).

**Comment by alisonrclarke** [comment]
Just attempted a build with root 6.22.00 and Yoda 1.8.3 and got a build failure on Yoda relating to pyroot:

```
/tmp/YODA-1.8.3/pyext/yoda/pyroot_helpers.hh: In function 'TObject* py_owned_to_root(PyObject*)':
/tmp/YODA-1.8.3/pyext/yoda/pyroot_helpers.hh:17:30: error: 'ObjectProxy_AsVoidPtr' is not a member of 'TPython'
   return (TObject*) TPython::ObjectProxy_AsVoidPtr(pyroot_obj);
                              ^~~~~~~~~~~~~~~~~~~~~
error: command '/opt/conda/bin/x86_64-conda_cos6-linux-gnu-c++' failed with exit status 1
make[2]: *** [Makefile:669: all-local] Error 1
```

It looks as though the YODA team have not yet ensured compatibility with the latest ROOT:  https://gitlab.com/hepcedar/yoda/-/issues/20

Should we hold off on this until the YODA issue has been fixed?

**Comment by alisonrclarke** [comment]
Looks like the method names of the TPython class have been changed:

https://root.cern/doc/v622/classTPython.html vs https://root.cern/doc/v620/classTPython.html

YODA is still using the old names.

**Comment by GraemeWatt** [comment]
OK, let's wait a few weeks to see if the YODA team make a new release soon, otherwise we can see if YODA 1.8.3 works with ROOT v6.20.00.

**Comment by alisonrclarke** [comment]
Logged https://gitlab.com/hepcedar/yoda/-/issues/22

**Comment by GraemeWatt** [comment]
Alternatively, since the `hepdata-converter` doesn't actually use the YODA interface to PyROOT, it could be disabled in the YODA build using `./configure --disable-root`.

**Comment by alisonrclarke** [comment]
Looks like the change to pyROOT means we'll have to make a change in `hepdata-converter`. Currently when running tests I get:

```
======================================================================
ERROR: test_simple_parse (test_rootwriter.ROOTWriterTestSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ksvf48/Documents/dev/HEPData/hepdata-converter/hepdata_converter/testsuite/__init__.py", line 65, in _inner
    function(*args, **kwargs)
  File "/Users/ksvf48/Documents/dev/HEPData/hepdata-converter/hepdata_converter/testsuite/__init__.py", line 65, in _inner
    function(*args, **kwargs)
  File "/Users/ksvf48/Documents/dev/HEPData/hepdata-converter/hepdata_converter/testsuite/test_rootwriter.py", line 58, in test_simple_parse
    hepdata_converter.convert(yaml_full_path, output,
  File "/Users/ksvf48/Documents/dev/HEPData/hepdata-converter/hepdata_converter/__init__.py", line 40, in convert
    writer.write(parser.parse(input), _output)
  File "/Users/ksvf48/Documents/dev/HEPData/hepdata-converter/hepdata_converter/writers/root_writer.py", line 456, in write
    output.ReadBuffer(buff, file_size)
TypeError: none of the 2 overloaded methods succeeded. Full details:
  bool TFile::ReadBuffer(char* buf, int len) =>
    TypeError: could not convert argument 1 (could not convert argument to buffer or nullptr)
  bool TFile::ReadBuffer(char* buf, Long64_t pos, int len) =>
    TypeError: takes at least 3 arguments (2 given)

----------------------------------------------------------------------
```

See https://root.cern/manual/python/#new-pyroot-backwards-incompatible-changes for details of changes.
